---
applications:
- instances: 1
  timeout: 180
  name: nccloudmessaging
  buildpack: sdk-for-nodejs
  command: npm start
  disk_quota: 1G
  memory: 128MB
  domain: mybluemix.net
  host: nccloud-messaging-beta
